{{- if .Values.authProxy.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kubeapps.oauth2_proxy-secret.name" . }}
  {{- if .namespace }}
  namespace: {{ .namespace }}
  {{- end }}
  labels:{{ include "kubeapps.labels" $ | nindent 4 }}
data:
  clientID: {{ required "You must fill \".Values.authProxy.clientID\" with the Client ID of the provider" .Values.authProxy.clientID | b64enc }}
  clientSecret: {{ required "You must fill \".Values.authProxy.clientSecret\" with the Client Secret of the provider" .Values.authProxy.clientSecret | b64enc }}
  cookieSecret: {{ required "You must fill \".Values.authProxy.cookieSecret\" with a 16, 24 or 32 byte base64 encoded seed string for secure cookies" .Values.authProxy.cookieSecret | b64enc }}
---
{{- end }}
